# Generated by Django 3.2.16 on 2022-10-11 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_banner_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
